# 1. numpy

In [1]:
# 如果你的電腦還沒安裝numpy，請先透過python pip管理套件安裝
!pip3 install numpy

You should consider upgrading via the '/opt/anaconda3/bin/python -m pip install --upgrade pip' command.


In [2]:
import numpy as np
print(np.__version__)

1.18.1


### np.array()

numpy基礎資料結構的方法，用以儲存一維至多維陣列(ndarray)

In [14]:
a = np.array(1)
print(a)

1
<class 'numpy.ndarray'>


In [12]:
b = np.array([1,2,3])
print(b)

[1 2 3]


In [13]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(type(c))

<class 'numpy.ndarray'>


透過ndarray進行矩陣運算

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
a * b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [30]:
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# 2. pandas

In [46]:
# 如果你的電腦還沒安裝pandas，請先透過python pip管理套件安裝
!pip3 install pandas

You should consider upgrading via the '/opt/anaconda3/bin/python -m pip install --upgrade pip' command.


In [47]:
import pandas as pd
print(pd.__version__)

1.1.5


### 透過pandas讀入csv或excel檔案

In [55]:
df = pd.read_csv('example.csv')
# df = pd.read_excel('example.xlsx')
df

id p_type s_name s_area_name  comment_count  \
0  1451580710262_PTT02R    bbs    Ptt       Stock           10.0   
1  1451580711002_PTT02R    bbs    Ptt       Stock           28.0   
2  1451580711248_PTT02R    bbs    Ptt       Stock           44.0   
3  1451581329544_PTT02R    bbs    Ptt       Stock           17.0   
4  1451583749064_PTT02R    bbs    Ptt       Stock           33.0   

       post_time                     title      author  \
0  2016/1/1 0:48        [新聞] 第三方支付 台灣普及關鍵年      Bokolo   
1  2016/1/1 0:50        [新聞] 曾銘宗：電子支付拼5年倍增      Bokolo   
2  2016/1/1 0:51        [請益] 交割帳戶什麼時候會扣款??     Lawleit   
3  2016/1/1 0:56  [新聞] 睽違8年　大宇資重返2016台北電玩展      Bokolo   
4  2016/1/1 1:42  [新聞] 人工撮合將成歷史！ 那斯達克啟用區塊鍊  DarkerDuck   

                                             content  
0  1.原文連結(必須檢附)：\nhttp://magazine.chinatimes.com/...  
1  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...  
2  寡人在手機上2014年12月30日買了生平第一支股票\n\n訊息顯示成交了 成交總金額約3萬...  
3  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...  
4  1.原文連結(必須檢附)：\nhttp://news.ltn.com.tw/news/bus...

### 選取特定欄位

In [51]:
# 方法一
df[['title', 'content']]

title                                            content
0        [新聞] 第三方支付 台灣普及關鍵年  1.原文連結(必須檢附)：\nhttp://magazine.chinatimes.com/...
1        [新聞] 曾銘宗：電子支付拼5年倍增  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...
2        [請益] 交割帳戶什麼時候會扣款??  寡人在手機上2014年12月30日買了生平第一支股票\n\n訊息顯示成交了 成交總金額約3萬...
3  [新聞] 睽違8年　大宇資重返2016台北電玩展  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...
4  [新聞] 人工撮合將成歷史！ 那斯達克啟用區塊鍊  1.原文連結(必須檢附)：\nhttp://news.ltn.com.tw/news/bus...

In [52]:
# 方法二
df.iloc[:, [6,8]]

title                                            content
0        [新聞] 第三方支付 台灣普及關鍵年  1.原文連結(必須檢附)：\nhttp://magazine.chinatimes.com/...
1        [新聞] 曾銘宗：電子支付拼5年倍增  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...
2        [請益] 交割帳戶什麼時候會扣款??  寡人在手機上2014年12月30日買了生平第一支股票\n\n訊息顯示成交了 成交總金額約3萬...
3  [新聞] 睽違8年　大宇資重返2016台北電玩展  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...
4  [新聞] 人工撮合將成歷史！ 那斯達克啟用區塊鍊  1.原文連結(必須檢附)：\nhttp://news.ltn.com.tw/news/bus...

### 選取特定行

In [53]:
df.iloc[[1,3], :]

id p_type s_name s_area_name  comment_count  \
1  1451580711002_PTT02R    bbs    Ptt       Stock           28.0   
3  1451581329544_PTT02R    bbs    Ptt       Stock           17.0   

       post_time                     title  author  \
1  2016/1/1 0:50        [新聞] 曾銘宗：電子支付拼5年倍增  Bokolo   
3  2016/1/1 0:56  [新聞] 睽違8年　大宇資重返2016台北電玩展  Bokolo   

                                             content  
1  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...  
3  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...

### 依照欄位條件篩選特定行

In [54]:
df[df['comment_count'] >= 30]

id p_type s_name s_area_name  comment_count  \
2  1451580711248_PTT02R    bbs    Ptt       Stock           44.0   
4  1451583749064_PTT02R    bbs    Ptt       Stock           33.0   

       post_time                     title      author  \
2  2016/1/1 0:51        [請益] 交割帳戶什麼時候會扣款??     Lawleit   
4  2016/1/1 1:42  [新聞] 人工撮合將成歷史！ 那斯達克啟用區塊鍊  DarkerDuck   

                                             content  
2  寡人在手機上2014年12月30日買了生平第一支股票\n\n訊息顯示成交了 成交總金額約3萬...  
4  1.原文連結(必須檢附)：\nhttp://news.ltn.com.tw/news/bus...

### 檢查與處理空值

In [57]:
df.isnull().any()

id               False
p_type           False
s_name           False
s_area_name      False
comment_count    False
post_time        False
title            False
author           False
content          False
dtype: bool

In [71]:
# 若有空值存在，最簡單的方法就是直接刪除該筆資料
df = df.dropna()
df = df.reset_index(drop = True)

### 表格合併

In [62]:
class1 = pd.DataFrame([['John', 20, 174, 63], 
                  ['Amy', 21, 162, 48],
                 ['May', 20, 170, 52],
                 ['Alan', 19, 192, 101]], columns = ['Name', 'Age', 'Height', 'Weight'])
class2 = pd.DataFrame([['Tim', 20, 179, 65], 
                  ['Howard', 19, 186, 88],
                 ['Austin', 24, 174, 69],
                 ['Laura', 24, 160, 50]], columns = ['Name', 'Age', 'Height', 'Weight'])
class1_info = pd.DataFrame([['John', 'M'], 
                  ['Amy', 'F'],
                 ['May', 'F'],], columns = ['Name', 'Gender'])
class1_updated = pd.DataFrame([['John', 21, 174, 67], 
                  ['Amy', 22, 162, 47],
                 ['May', 21, 170, 54],
                 ['Alan', 20, 192, 98]], columns = ['Name', 'Age', 'Height', 'Weight'])

In [63]:
class1

Name  Age  Height  Weight
0  John   20     174      63
1   Amy   21     162      48
2   May   20     170      52
3  Alan   19     192     101

In [65]:
class2

Name  Age  Height  Weight
0     Tim   20     179      65
1  Howard   19     186      88
2  Austin   24     174      69
3   Laura   24     160      50

In [81]:
class1_info

Name Gender
0  John      M
1   Amy      F
2   May      F

In [82]:
class1_updated

Name  Age  Height  Weight
0  John   21     174      67
1   Amy   22     162      47
2   May   21     170      54
3  Alan   20     192      98

1. 將兩張表直接相接合併（concat)

In [70]:
school = pd.concat([class1, class2])
school = school.reset_index(drop = True)
school

Name  Age  Height  Weight
0    John   20     174      63
1     Amy   21     162      48
2     May   20     170      52
3    Alan   19     192     101
4     Tim   20     179      65
5  Howard   19     186      88
6  Austin   24     174      69
7   Laura   24     160      50

2. 將兩張表依相關欄位合併(merge)

In [73]:
pd.merge(class1, class1_info, on = 'Name', how = 'left')

Name  Age  Height  Weight Gender
0  John   20     174      63      M
1   Amy   21     162      48      F
2   May   20     170      52      F
3  Alan   19     192     101    NaN

In [78]:
pd.merge(class1, class1_info, on = 'Name', how = 'inner')

Name  Age  Height  Weight Gender
0  John   20     174      63      M
1   Amy   21     162      48      F
2   May   20     170      52      F

3. 將兩張表依索引index合併(merge)

In [80]:
class1.join(class1_updated, lsuffix='_before', rsuffix = '_after')

Name_before  Age_before  Height_before  Weight_before Name_after  Age_after  \
0        John          20            174             63       John         21   
1         Amy          21            162             48        Amy         22   
2         May          20            170             52        May         21   
3        Alan          19            192            101       Alan         20   

   Height_after  Weight_after  
0           174            67  
1           162            47  
2           170            54  
3           192            98

### 寫出檔案

In [ ]:
school.to_csv('school.csv', index = False)

# 3. monpa

In [83]:
# 如果你的電腦還沒安裝monpa，可以透過python pip管理套件安裝
!pip3 install pandas

You should consider upgrading via the '/opt/anaconda3/bin/python -m pip install --upgrade pip' command.


In [84]:
import monpa

+---------------------------------------------------------------------+
  Welcome to MONPA: Multi-Objective NER POS Annotator for Chinese
+---------------------------------------------------------------------+
已找到 model檔。Found model file.


In [86]:
df = pd.read_csv('example.csv')
df

id p_type s_name s_area_name  comment_count  \
0  1451580710262_PTT02R    bbs    Ptt       Stock           10.0   
1  1451580711002_PTT02R    bbs    Ptt       Stock           28.0   
2  1451580711248_PTT02R    bbs    Ptt       Stock           44.0   
3  1451581329544_PTT02R    bbs    Ptt       Stock           17.0   
4  1451583749064_PTT02R    bbs    Ptt       Stock           33.0   

       post_time                     title      author  \
0  2016/1/1 0:48        [新聞] 第三方支付 台灣普及關鍵年      Bokolo   
1  2016/1/1 0:50        [新聞] 曾銘宗：電子支付拼5年倍增      Bokolo   
2  2016/1/1 0:51        [請益] 交割帳戶什麼時候會扣款??     Lawleit   
3  2016/1/1 0:56  [新聞] 睽違8年　大宇資重返2016台北電玩展      Bokolo   
4  2016/1/1 1:42  [新聞] 人工撮合將成歷史！ 那斯達克啟用區塊鍊  DarkerDuck   

                                             content  
0  1.原文連結(必須檢附)：\nhttp://magazine.chinatimes.com/...  
1  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...  
2  寡人在手機上2014年12月30日買了生平第一支股票\n\n訊息顯示成交了 成交總金額約3萬...  
3  1.原文連結(必須檢附)：\nhttp://www.appledaily.com.tw/re...  
4  1.原文連結(必須檢附)：\nhttp://news.ltn.com.tw/news/bus...

In [89]:
df['content'][2]

'寡人在手機上2014年12月30日買了生平第一支股票\n\n訊息顯示成交了 成交總金額約3萬5千\n\n收盤後查戶頭錢沒手\n\n後來收信說會在隔天10點前扣款\n\n下面還附註扣不到款會有刑責  要我把戶頭錢準備好\n\n但是到現在我戶頭錢還是沒少\n\n究竟什麼時候會扣款呢??\n\n--\n'

In [90]:
tokens = monpa.cut(df['content'][2])
tokens

['寡人',
 '在',
 '手機',
 '上',
 '2014年',
 '12月',
 '30日',
 '買',
 '了',
 '生平',
 '第一',
 '支',
 '股票',
 ' ',
 ' ',
 '訊息',
 '顯示',
 '成交',
 '了',
 ' ',
 '成交總',
 '金額',
 '約',
 '3萬5千',
 ' ',
 ' ',
 '收盤',
 '後',
 '查',
 '戶頭錢',
 '沒',
 '手',
 ' ',
 ' ',
 '後來',
 '收信',
 '說',
 '會',
 '在',
 '隔天',
 '10',
 '點',
 '前',
 '扣款',
 ' ',
 ' ',
 '下面',
 '還',
 '附',
 '註扣',
 '不',
 '到',
 '款',
 '會',
 '有',
 '刑責',
 ' ',
 ' ',
 '要',
 '我',
 '把',
 '戶頭錢',
 '準備',
 '好',
 ' ',
 ' ',
 '但是',
 '到',
 '現在',
 '我',
 '戶頭錢',
 '還是',
 '沒',
 '少',
 ' ',
 ' ',
 '究',
 '竟',
 '什麼',
 '時候',
 '會',
 '扣款',
 '呢',
 '?',
 '?',
 ' ',
 ' ',
 '-',
 '-']

In [93]:
df['content'][0]

'1.原文連結(必須檢附)：\nhttp://magazine.chinatimes.com/moneyweekly/20151231003706-300201\n\n2.原文內容：\n第三方支付專法上路，看好市場龐大商機，遊戲廠商、銀行業者紛紛搶進，如針對陸客推\n出「手機掃碼支付」，以及讓消費者能在線上藉由銀行帳戶即完成電子商務支付。\n\n網路興起之後，電商蓬勃發展，其中第三方支付也隨之興起，去(2015)年台灣通過第三方\n支付專法，下半年多數廠商紛紛取得執照，今年可望付諸應用，因此外界預估，2016將會\n是第三方支付在台灣普及的關鍵一年。\n\n遊戲廠商近幾個月以來積極搶進第三方支付市場，對營收挹注明顯，橘子(6180)成為大贏\n家，橘子十一月營收表現出色，智冠(5478)、歐買尬(3687)等第三方支付相關廠商十一月\n業績則大多持穩。\n\n橘子十一月財報顯示，其營收8.93億元，月增12.7％、年增5.9％，為去年單月營收次高\n、歷年同期新高；前十一月合併營收88.48億元，年增7.2％，預估今年營收可望突破百億\n元大關。\n\n智冠十一月營收12.11億元，月減1.8％、年增4.9％。十二月取得第三方支付執照，旗下\n支付子公司智付寶也已開始運作，同樣將在今年首季提供相關服務。\n\n歐買尬十一月營收六九七三萬元，月增5.3％、年增102.5％，旗下支付子公司歐付寶已取\n得第三方支付執照，日前支付App也搶先上線。\n\n遊戲商銀行爭奪第三方支付市場\n\n除了遊戲廠商，銀行也搶進第三方支付市場。玉山銀行與螞蟻金服集團旗下支付寶合作，\n針對來台旅遊陸客推出「手機掃碼支付」跨境Ｏ２Ｏ創新金融服務，陸客只要透過支付寶\n錢包，就可以在台灣各大百貨、連鎖超商、夜市、商圈等進行消費，預計將有超過五千家\n商店加入手機掃碼支付行列，為全台提供最多商戶使用的銀行。\n\n玉山銀行指出，為推廣更多陸客來台使用，日前搭配雙十二話題，支付寶推出雙十二活動\n，包含百貨、超商、名特產店等，使用支付寶付款可獲得八折以上的優惠，夜市商圈更有\n一元享美食活動，每位支付寶用戶皆可以一元人民幣兌換一百元新台幣以下的夜市美食，\n雙十二當天更祭出合作商家最低五折的優惠，全額由支付寶贊助，行銷台灣的美食與商圈\n。\n\n玉山銀行聚焦金融創新，提供最好的數位金融服務，

In [95]:
from monpa import utils

In [96]:
sentence_list = utils.short_sentence(df['content'][0])

tokens = []
for sentence in sentence_list:
    tokens.extend(monpa.cut(sentence))
tokens

['1',
 '.',
 '原文',
 '連結',
 '(',
 '必須',
 '檢附',
 ')',
 '：',
 ' ',
 'http://magazine.chinatimes.com/moneyweekly/20151231003706',
 '-',
 '300201',
 ' ',
 ' ',
 '2',
 '.',
 '原文',
 '內容',
 '：',
 ' ',
 '第三',
 '方',
 '支付',
 '專法',
 '上路',
 '，',
 '看好',
 '市場',
 '龐大',
 '商機',
 '，',
 '遊戲',
 '廠商',
 '、',
 '銀行',
 '業者',
 '紛紛',
 '搶進',
 '，',
 '如',
 '針對',
 '陸客',
 '推',
 ' 出',
 '「',
 '手機',
 '掃碼',
 '支付',
 '」',
 '，',
 '以及',
 '讓',
 '消費者',
 '能',
 '在',
 '線',
 '上',
 '藉由',
 '銀行',
 '帳戶',
 '即',
 '完成',
 '電子',
 '商務',
 '支付',
 '。',
 '網路',
 '興起',
 '之後',
 '，',
 '電商',
 '蓬勃',
 '發展',
 '，',
 '其中',
 '第三',
 '方',
 '支付',
 '也',
 '隨之',
 '興起',
 '，',
 '去',
 '(',
 '2015',
 ')',
 '年',
 '台灣',
 '通過',
 '第三',
 '方',
 ' ',
 '支付',
 '專法',
 '，',
 '下',
 '半',
 '年',
 '多數',
 '廠商',
 '紛紛',
 '取得',
 '執照',
 '，',
 '今年',
 '可望',
 '付',
 '諸',
 '應用',
 '，',
 '因此',
 '外界',
 '預估',
 '，',
 '2016',
 '將',
 '會',
 ' ',
 '是',
 '第三',
 '方',
 '支付',
 '在',
 '台灣',
 '普及',
 '的',
 '關鍵',
 '一',
 '年',
 '。',
 '遊戲',
 '廠商',
 '近',
 '幾',
 '個',
 '月',
 '以來',
 '積極',
 '搶進',
 '第三',
 '方',
 '支付',


# 4. sklearn

### (1). linear regression

In [98]:
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [99]:
df = datasets.fetch_california_housing()

In [100]:
X_train, X_test, y_train, y_test = train_test_split(df['data'], df['target'], test_size = .2)

In [105]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [107]:
mean_squared_error(y_test, y_pred)

0.5193479601463054

### (2). logistic regression

In [127]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [109]:
df = datasets.load_iris()

In [112]:
X_train, X_test, y_train, y_test = train_test_split(df['data'], df['target'], test_size = .2)

In [117]:
clf = LogisticRegression(max_iter = 2000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [118]:
accuracy_score(y_test, y_pred)

0.9666666666666667

In [129]:
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0, 14,  1],
       [ 0,  0,  7]])

### (3). clustering

In [ ]:
from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [107]:
df = datasets.load_iris()

In [108]:
X_train, X_test, y_train, y_test = train_test_split(df['data'], df['target'], test_size = .2)

In [112]:
kmeans = KMeans(n_clusters = 3)
kmeans.fit(X_train)
y_pred = kmeans.predict(X_test)

In [113]:
y_pred

array([1, 0, 0, 1, 2, 1, 1, 0, 1, 2, 1, 0, 0, 1, 2, 0, 0, 1, 1, 1, 2, 1,
       2, 1, 0, 0, 0, 2, 0, 2], dtype=int32)